---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

---
kind: pipeline
name: default-windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-2004
    settings:
      depth: 20

---
kind: pipeline
name: default-windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: rancher/drone-images:git-20H2
    settings:
      depth: 20